### ISSUE TITLE
MQTTPacket class >> #readFrom: raises PrimitiveFailed

### ISSUE THREAD

**Issue by JurajKubelka** [svenvc/mqtt#1]
The `next` message on the first line, `byte := binaryStream next.`, produces `PrimitiveFailed: primitive #primSocketReceiveDataAvailable: in Socket failed`. 

Steps to reproduce: Subscribe to a topic, save, close and open the image.
Script example:

```
finish := false.

client := MQTTExperimentalClient new
	host: 'iot.eclipse.org';
	port: 1883;
	clientId: 'Listener';
	open;
	subscribeToTopic: '/pharo/fogbugz/cases';
	yourself.

[ client
	runWith: [ :message |
		Transcript cr; show: message contents asString; cr.
		finish ifTrue: [ ConnectionClosed signal ] ]
] forkAt: Processor userBackgroundPriority named: 'Listener'.
```

[stack.txt](https://github.com/svenvc/mqtt/files/730964/stack.txt)

**Comment by svenvc** [comment]
Well, that is normal, since by closing/opening the image the socket and socket stream get closed and thus reading from it fails, as it should.

I am personally no fan of sugaring exceptions: I like to report things as they are.

I'll think a bit more about it, if you have any suggestions, please tell me.

**Comment by JurajKubelka** [comment]
I understand. Than maybe we could create another MQTT client that is more robust. It could re-establish subscriptions.

And `MQTTExperimentalClient` class comment could explain it a bit. What do you think?

**Comment by JurajKubelka** [comment]
I agree to close this issue. I catch PrimitiveFailed.

**Comment by JurajKubelka** [comment]
According to the change you made for #2, maybe this could be also signaled by `ConnectionClosed`. What do you think?

**Comment by svenvc** [comment]
I think that is not the same thing; trying to use a socket after image save is really a big error; it should fail hard. It would be like referring to a file that is gone. Well, that is how I feel about it.

**Comment by JurajKubelka** [comment]
OK. It implies that mqtt users have to deal with ConnectionClosed and PrimitiveFailed exceptions. I think in both cases they will do the same.
