### ISSUE TITLE
MQTTPacket class>>readFrom: does not understand #'>>'

### ISSUE THREAD

**Issue by JurajKubelka** [svenvc/mqtt#2]
It happens twice to me. Not sure how to reproduce it. The thing is that `binaryStream next` returns nil.

[stack.txt](https://github.com/svenvc/mqtt/files/731032/stack.txt)

**Comment by svenvc** [comment]
The really silly thing about the standard stream library including socket streams is that #next returns nil on end of file. The Zdc stream respect that for backwards compatibility reasons. But it is totally wrong of course.

Anyway, it is basically again a problem of the underlying socket stream or connection that is gone or not working properly.

Like the other issue: I will think a bit about it.

**Comment by JurajKubelka** [comment]
@svenvc Can we fix this? I do not want to catch MessageNotUnderstood error and this happens whenever connection is lost. You can run the script from #1 using `localhost` and stop the server. Maybe there could be a `MQTTEmptyPacket` that is returned and ignored in higher level. Maybe it could return `false` while calling `isApplicationMessage`. What do you think?

**Comment by JurajKubelka** [comment]
It can likely happen also in `readRemainingLengthFrom:`. Maybe there are other places.

**Comment by svenvc** [comment]
Let's start with the primary one (which is the first byte read)

===
Name: MQTT-Core-SvenVanCaekenberghe.3
Author: SvenVanCaekenberghe
Time: 21 February 2017, 10:14:02.05448 pm
UUID: 60ae9c98-7205-0d00-a648-1a340c273db3
Ancestors: MQTT-Core-SvenVanCaekenberghe.2

Signal ConnectionClosed when MQTTPacket class>>#readFrom: gets nil from binary stream #next 
===

Would that help ?

**Comment by JurajKubelka** [comment]
That's cool! It works :-) Thanks!

**Comment by JurajKubelka** [comment]
I have added other connection checks. Hopefully you will agree:

```
Name: ConfigurationOfMQTT-JurajKubelka.6
Author: JurajKubelka
Time: 22 February 2017, 11:50:23.466256 pm
UUID: 0cf65b69-8b05-0d00-a360-d9f909aa087c
Ancestors: ConfigurationOfMQTT-JurajKubelka.5

Messages #ping, readMessage, sendMessate:toTopic:, subscribeToTopic:, and unsubscribeFromTopic: raise ConnectionClosed if client is not connected. Such behavior is coherent with other scenarios where it raises ConnectionClosed.
```
