### ISSUE TITLE
Test cases failures on Travis

### ISSUE THREAD

**Issue by JurajKubelka** [svenvc/mqtt#3]
Test cases on Travis fail, but it is not clear why. They also fails for `localhost`. Observing all builds, it is not deterministic. Each build has different failures. See https://travis-ci.org/JurajKubelka/mqtt/builds

If I run it locally following the instructions:
```
To reproduce the failed build locally, download smalltalkCI and try to run something like:
  /path/to/run.sh -s Pharo-5.0 --headful /path/to/project/.smalltalk.ston
```
It works. Maybe a timeout should be longer?
Would be nice to fix it. Any idea?

**Comment by svenvc** [comment]
If it seems random (i.e. they sometimes do really pass) then increasing the timeout could be a good thing to try
