### ISSUE TITLE
Assertion failed in MQTTPublish(MQTTPacket)>>readRemainingLengthFrom:

### ISSUE THREAD

**Issue by maxbareis** [svenvc/mqtt#4]
Hi,
it seems that the Assertion fails as soon as the binaryStream has more than 3 bytes:
```
readRemainingLengthFrom: binaryStream
	| length multiplier byte |
	length := 0.
	multiplier := 1.
	[
		byte := binaryStream next.
		length := length + ((byte bitAnd: 127) * multiplier).
		multiplier := multiplier * 128.
		self assert: multiplier < (128 ** 3).
		(byte bitAt: 8) = 1 ] whileTrue.
	^ length
```
Is this intended and if yes why? The readBuffer of one of the mqtt packets I have received has 4096 bytes, how can I read them?

Regards
Max

**Comment by svenvc** [comment]
Hi,

The above code reads the length, which is specified in one or more bytes. It does indeed only support lengths specified as 3 bytes. But that is already more than the total allowed packet length.

But I would have to check the specs.

How does this fail for you ? Can you provide a snippet that fails ?

Sven

**Comment by maxbareis** [comment]
Hi Sven,
the code snippet is pretty simple, I am subscribing to the 'hermes/#' path where the snips (https://snips.ai) voice assistant is posting messages:
```
openMQTTConnection
    MQTTExperimentalClient new
       open;
       subscribeToTopic: 'hermes/#';
       runWith: [ :message |
         self parseMessage:message ] 
```
```
parseMessage
: aMQTTPublish 
	(aMQTTPublish topic = '/hotword/default/detected') ifTrue: [ self startListening: aMQTTPublish ].
	Delay forSeconds: 10.
```
self startListening does not exist but is never called. As soon as a message is sent on /hotword/default/detected the above AssertionFailure is thrown.
Currently I do not know how to serialize and attach the Stream that is sent to readRemainingLengthFrom: 

Regards
Max

**Comment by svenvc** [comment]
Hi Max,

I checked the spec again and indeed I found http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718023 where is says the remaining length can be encoded using up to 4 bytes.

Your payload probably exceeds 2 097 151 in size.

Could you try changing the assert to

    self assert: multiplier <= (128 ** 3).

so with the condition <= instead of < to allow for 4 bytes. This seems like a stupid one-off error.

Thx for reporting this issue !

Sven

**Comment by maxbareis** [comment]
Tests were positive. See pull request.
